first commit
pluwiq/business-reporting pull request #1
Opened 2024-07-29 20:59 UTC by pluwiq

2024-07-30 13:20 UTC, TsikhanauDzmitry commented on exporters/json_exporter.rb
> +      file.write(JSON.pretty_generate(@report_data))
Что делает метод `pretty_generate`?

2024-07-30 13:20 UTC, TsikhanauDzmitry commented on exporters/json_exporter.rb
> +    end
Нельзя ли написать это одной строчкой?

2024-07-30 13:21 UTC, TsikhanauDzmitry commented on main.rb
> +export_file_csv = 'report.csv'
Может это лучше сделать константами?

2024-07-30 13:21 UTC, TsikhanauDzmitry commented on main.rb
> +logger.level = Logger::INFO
Зачем это было добавлено?

2024-07-30 13:22 UTC, TsikhanauDzmitry commented on main.rb
> +}
Внутри хэша можно и символы использовать, как ключи

2024-07-30 13:25 UTC, TsikhanauDzmitry commented on main.rb
> +  print "Your choice: "
?

2024-07-30 13:28 UTC, TsikhanauDzmitry commented on main.rb
> +  print "Your choice: "
?

2024-07-30 13:28 UTC, TsikhanauDzmitry commented on main.rb
> +def display_menu
Почему эти методы тут?

2024-07-30 13:29 UTC, TsikhanauDzmitry commented on main.rb
> +    end
Что будет при вводе букв?

2024-07-30 13:34 UTC, TsikhanauDzmitry commented on main.rb
> +  end
Что это и зачем?

2024-07-30 13:36 UTC, TsikhanauDzmitry commented on main.rb
> +end
Можно просто сделать какой-нибудь метод под это, а его вынести вместе с остальными в какой-нибудь `module BusinessWorker`

2024-07-30 13:39 UTC, TsikhanauDzmitry commented on reports/base_report.rb
> +    @data = data
Может быть лучше под это сделать метод какой-нибудь? Тип `validate_data`

2024-07-30 13:40 UTC, TsikhanauDzmitry commented on reports/base_report.rb
> +    @data = data
Лучше не делать ничего подобного в инициализации

2024-07-30 13:41 UTC, TsikhanauDzmitry commented on reports/base_report.rb
> +  protected
Чем `protected` отличаются от `private`? Почем ты использовала `protected`?

2024-07-30 13:43 UTC, TsikhanauDzmitry commented on reports/second_report.rb
> +    industry_counts.transform_values(&:count)
Что делают методы `group_by` и `transform_values`?

2024-07-30 13:44 UTC, TsikhanauDzmitry commented on reports/third_report.rb
> +  end
Подумай, как можно использовать меньше локальных переменных

2024-07-30 13:45 UTC, TsikhanauDzmitry commented on services/data_loader.rb
Что там про одну строчку?

2024-07-30 13:46 UTC, TsikhanauDzmitry commented on services/data_loader.rb
> +  def self.load_data(file_path:)
Это точно `self` метод для класса?

2024-07-30 13:46 UTC, TsikhanauDzmitry commented on services/report_generator.rb
> +  end
Подумай, как можно использовать меньше локальных переменных

2024-07-30 15:17 UTC, pluwiq commented on exporters/base_exporter.rb
> +  end
`@report_data` содержит в себе данные отчета, которые необходимо экспортировать. Это может быть массив хэшей, где каждый хэш представляет собой строку данных с ключами, соответствующими заголовкам колонок.

Например для отчета `FirstReport`, который выводит компании с числом сотрудников больше или равно 100, `report_data` будет массивом хэшей.

2024-07-31 07:48 UTC, pluwiq commented on exporters/json_exporter.rb
> +      file.write(JSON.pretty_generate(@report_data))
метод `pretty_generate` из библиотеки `json` используется для создания форматированного строкового представления объекта в формате JSON.  Форматирование включает отступы, пробелы и переносы строк, что делает JSON более читаемым.

2024-07-31 07:58 UTC, pluwiq commented on main.rb
> +logger.level = Logger::INFO
Логирование предоставляет возможность отслеживать и записывать различные события, ошибки и информацию о работе программы. Используется для диагностики проблем, анализа поведения приложения и ведения истории событий. В проекте логирование используется для записи информации о процессе генерации отчетов и обработки ошибок.

2024-07-31 08:18 UTC, pluwiq commented on main.rb
> +    end
необходимо добавить проверку на то, что вводимые данные являются числом

2024-07-31 08:26 UTC, pluwiq commented on main.rb
> +  end
мы всегда возвращаем пустой хэш независимо от типа отчета, чтобы упростить обработку возвращаемого значения в коде т.к он всегда будет ожидать хэш. Но лучше будет переписать код в виде 

```
case report_type
  when :first_report
    { min_employees: validate_min_employees }
  else
    {}
  end
```

2024-07-31 10:27 UTC, pluwiq commented on reports/base_report.rb
> +  protected
private методы могут быть вызваны только в контексте текущего объекта и нельзя явно указать объект при вызове метода.

protected` методы могут быть вызваны внутри того же класса и его подклассов и могут быть вызваны на другом экземпляре того же класса или его подклассов.

В данном случае методы `validate_data`, `filter_data`, `sort_data` и `limit_data` объявлены как `protected`, чтобы они могли быть доступны не только внутри класса `BaseReport`, но и в подклассах.

(к примеру)
Если методы `filter_data`, `sort_data` и `limit_data` объявлены как `private`, то вызов `filter_data` внутри `FirstReport` приведет к ошибке, потому что `private` методы не могут быть вызваны из подклассов. Но если они объявлены как `protected`, то `FirstReport` может использовать эти методы.

2024-07-31 10:38 UTC, pluwiq commented on reports/second_report.rb
> +    industry_counts.transform_values(&:count)
метод group_by используется для группировки элементов коллекции и возвращает хэш, где ключами являются результаты применения блока к элементам коллекции, а значениями — массивы элементов, соответствующих каждому ключу.

метод transform_values используется для преобразования значений хэша на основе заданного блока. Он возвращает новый хэш с теми же ключами, но с измененными значениями.

2024-07-31 10:41 UTC, pluwiq commented on reports/third_report.rb
> +  end
будем использовать (method chaining) - техника, при которой несколько методов вызываются последовательно, где каждый последующий метод вызывается на результате предыдущего. Это позволяет писать более компактный код, уменьшая количество промежуточных переменных.

2024-07-31 11:00 UTC, pluwiq commented on services/data_loader.rb
> +  def self.load_data(file_path:)
использование `self` в методе класса позволяет определить метод, который можно вызывать напрямую на самом классе, а не на его экземплярах.

методы класса полезны, когда действие, которое они выполняют, не зависит от состояния конкретного объекта класса. В проекте метод `load_data` загружает данные из файла и возвращает их, и это действие не требует создания экземпляра класса `DataLoader`.

2024-07-31 13:29 UTC, TsikhanauDzmitry requested changes

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on business_worker.rb
> +  end
Мне не нравится этот метод. Много улучшений мы уже ранее обсуждали, например:
```
  def self.validate_min_employees
    loop do
      print 'Enter the minimum number of employees: '
      error_message = validate_input(input = gets.chomp)
      return input unless error_message

      puts error_message
    end
  end
```

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on business_worker.rb
> +  end
думаю, что было бы круто возвращать булевские значения: мол прошло или нет валидацию

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on business_worker.rb
> +  def self.run_report_generation(report_generator, logger, data_file, export_file_json, export_file_csv)
?

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on business_worker.rb
> +    additional_args = get_additional_args(report_type: report_type)
?

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on business_worker.rb
> +    print "Your choice: "
Что делает `print`?

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on business_worker.rb
> +  end
Можно разделить на 2 метода, а этот метод будет возвращать только массив, в котором вызываются 2 метода

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on exporters/base_exporter.rb
> +  end
Иногда разработчики оставляют комментарии с такими данными, чтобы было проще. Оформи эту информацию в четкий коммент с инструкциями

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on exporters/json_exporter.rb
> +  end
Что с отступами?

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on main.rb
> +}
Может быть использовать это, как константы?

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on reports/base_report.rb
> +    unless data.is_a?(Array) && data.all? { |row| row.is_a?(Hash) }
Что я говорил про `unless` блоки?

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on reports/base_report.rb
> +    @data = data
Нельзя ли сделать метод `validate_data` таким, чтобы он возвращал провалидированные данные? Тогда эти 2 строчки можно и объединить

2024-07-31 13:29 UTC, TsikhanauDzmitry commented on reports/base_report.rb
> +  def sort_data(key:, order: :asc)
Что такое `:ask` и `:desc`?

2024-07-31 14:32 UTC, pluwiq commented on business_worker.rb
> +    print "Your choice: "
`print` выводит текст без добавления символа новой строки, оставляя курсор на той же строке. В отличии от `puts`, который выводит текст и добавляет символ новой строки ` (\n)` после вывода, перемещая курсор на следующую строку.

2024-07-31 15:02 UTC, pluwiq commented on reports/base_report.rb
> +  def sort_data(key:, order: :asc)
`:asc` - символ, который используется для обозначения сортировки по возрастанию. Это значение по умолчанию для параметра `order`. Когда сортировка выполняется по возрастанию, элементы упорядочиваются от меньшего к большему.

`:desc` - символ, который используется для обозначения сортировки по убыванию. Когда сортировка выполняется по убыванию, элементы упорядочиваются от большего к меньшему.

2024-08-01 12:39 UTC, TsikhanauDzmitry requested changes

2024-08-01 12:39 UTC, TsikhanauDzmitry commented on business_worker.rb
> +    end
Думаю, что тут можно еще чище и меньше написать

2024-08-01 14:45 UTC, pluwiq commented on reports/base_report.rb
> +    if !data.is_a?(Array) || !data.all? { |row| row.is_a?(Hash) }
метод `all?` проверяет, соответствуют ли все элементы коллекции (например, массив или хэш) определенному условию, заданному в блоке. Если все элементы удовлетворяют условию, метод возвращает `true`, в противном случае `false`.

`data.all? { |row| row.is_a?(Hash) }` возвращает `true`, если все элементы в массиве `data` являются хэшами.
`!data.all? { |row| row.is_a?(Hash) }` инвертирует результат, возвращая `true`, если хотя бы один элемент в массиве `data` не является хэшом.

существует обратный метод `none?` который возвращает `true`, если ни один элемент коллекции не соответствует заданному условию.

2024-08-02 08:53 UTC, TsikhanauDzmitry approved these changes

2024-08-02 08:57 UTC, merged